#!/usr/bin/env bash

openssl genrsa -des3 -out example.com.key 1024
openssl rsa -des -in example.com.key -pubout > example.com.pub
openssl req -new -key example.com.key -out example.com.csr
openssl x509 -req -days 365 -in example.com.csr -signkey example.com.key -out example.com.crt
