#!/usr/bin/env bash

scripts_folder=$(dirname $0)
last_tutorial_folder=$($scripts_folder/get-last-tutorial-folder)

echo $last_tutorial_folder
cd $last_tutorial_folder
export PATH=$PATH:$PWD/bin
./bin/merge
